---
title: "HW3_Graphics"
author: "Skyler Roh 23313980"
date: "February 13, 2015"
output: pdf_document
---

```{r}
library("XML")
library("RColorBrewer")
flu = readHTMLTable("http://www.cdc.gov/flu/weekly/weeklyarchives2013-2014/data/whoAllregt39.htm", colClasses = "numeric")[[1]]
names(flu) = c("Wk","A.H1", "A.09H1", "A.H3", "A.NA", "A.NA2", "B", "Tot", "Per")
```


```{r}
TITLE = "Influenza Positive Tests Reported to CDC by U.S. WHO/NREVSS \nCollaborating Laboratories, National Summary, 2013-14"
XLAB = "Week"
YLAB = "Number of Positive Specimens"

flu$Wk[1:13] = paste("2013", as.character(flu$Wk[1:13]), sep = "")
flu$Wk[14:22] = paste("20140", as.character(flu$Wk[14:22]), sep = "")
flu$Wk[23:52] = paste("2014", as.character(flu$Wk[23:52]), sep = "")
flu$Wk = as.factor(flu$Wk)

myColors = c(brewer.pal(9, "Set1")[c(6, 5, 1, 4, 3, 9)]) 
```


```{r, plot1, mar = c(4, 4, 6, 1)}
layout(matrix(c(1, 2, 1, 1, 2, 1, 1, 1, 1), 3, 3, byrow = TRUE), widths = c(.5, .45, .05), heights = c(.25, .25, .5))

#plot1
plot(x= flu$Wk, y = NULL, type = "n", xlab = XLAB, ylab = YLAB, main = TITLE, ylim = c(0, 5500), yaxt = "n", xlim = c(0, 52), xaxt = "n", bty ="n", cex.lab = 1.5, cex.main = 2)

axis(1, at = 0:52, labels = FALSE, pos = 0, tck = -0.01)
text(x = seq(-.55, 51, by = 2), y = 0, labels = flu$Wk[seq(1, 52, by = 2)], srt = 45, pos = 1, xpd = TRUE, cex = .7, offset = 1.1)

axis(2, at = seq(0, 5500, by = 500), labels = FALSE, pos = 0, tck = -0.01)
text(x = 0, y = seq(0, 5500, by = 500), labels = seq(0, 5500, by = 500), pos = 2, xpd = TRUE, cex = .9, offset = .6)

lines(flu$A.NA2 ~ flu$Wk, xaxt = "n", xpd = TRUE, col = myColors[1], lwd = 2.5)
lines(flu$A.09H1 ~ flu$Wk, col = myColors[2], lwd = 2.5)
lines(flu$A.H3 ~ flu$Wk, xaxt = "n", xpd = TRUE, col = myColors[3], lwd = 2.5)
lines(flu$A.NA ~ flu$Wk, xaxt = "n", xpd = TRUE, col = myColors[4], lwd = 2.5)
lines(flu$B ~ flu$Wk, xaxt = "n", xpd = TRUE, col = myColors[5], lwd = 2.5) 

legend(x = 0, y = 5250, legend = c("A(Subtyping not performed)", "2009 H1N1", "A(H3)", "H3N2v", "B", "Percent Positive"), fill = myColors, bty = "n", cex = .8)


#plot 2
plot(x= flu$Wk, y = NULL, type = "n", ylab = "percent positive", ylim = c(0, 40), yaxt = "n", xlab = "", xlim = c(0, 52), xaxt = "n", pch = 19, cex =.001, bty = "n")

axis(1, at = 0:52, labels = FALSE, pos = 0, tck = -0.01)
text(x = seq(-.55, 51, by = 4), y = 0, labels = flu$Wk[seq(1, 52, by = 4)], srt = 45, pos = 1, xpd = TRUE, cex = .7, offset = 1.1)

axis(2, at = seq(0, 40, by = 5), labels = FALSE, pos = 0, tck = -0.01)
text(x = 0, y = seq(0, 40, by = 5), labels = seq(0, 40, by = 5), pos = 2, xpd = TRUE, cex = .9, offset = .6)

lines(flu$Per ~ flu$Wk, col = myColors [6], lwd = 2.5)
```
